### ISSUE TITLE
I doesn't do anything

### ISSUE THREAD

**Issue by tvargheseH** [jotux/GccMapVisualizer#2]
There is no code here and it doesn't do anything...

**Comment by jotux** [comment]
There are a few things to know if you're new to github and git.

1.  There is an about section of every repository where you can put links. A lot of people hosting applications on github will put a link to the sample application there. 

![Untitled](https://user-images.githubusercontent.com/31179/211174473-4ee34b23-0bbb-4879-bb6d-3c2e257bfe22.png)

2. Git repositories can have more than one branch. This repository has a branch called gh-pages.
![branch](https://user-images.githubusercontent.com/31179/211174498-506dc49f-b10c-414a-8657-17e4398d0258.png)

3. Github can host pages for your projects and serve code from your repository. You can read about it here: https://pages.github.com/

**Comment by tvargheseH** [comment]
I submitted a map file and absolutely nothing happened...

May be I need to wait a long time?  If so, how long?

**Comment by jotux** [comment]
If you would like help troubleshooting you'll need to post the map file you're trying to parse here, otherwise I have no way of knowing what the problem could be.
